id = "lalrpop"
name = "LALRPOP"
version = "0.1.2"
schema_version = 1
authors = ["LighghtEeloo"]
description = "LALRPOP grammar support powered by lalrpop-lsp"
repository = "https://github.com/LighghtEeloo/lalrpop-lsp"

[grammars.lalrpop]
repository = "https://github.com/LighghtEeloo/lalrpop-lsp"
rev = "930d43ffbc29db79db7692fe4fa4c159a0339e24"
path = "grammars/lalrpop"

[language_servers.lalrpop-lsp]
name = "LALRPOP Language Server"
languages = ["LALRPOP"]

[language_servers.lalrpop-lsp.language_ids]
LALRPOP = "lalrpop"
