id = "lalrpop"
name = "LALRPOP"
version = "0.1.2"
schema_version = 1
authors = ["LighghtEeloo"]
description = "LALRPOP grammar support powered by lalrpop-lsp"
repository = "https://github.com/LighghtEeloo/lalrpop-lsp"

[grammars.lalrpop]
repository = "https://github.com/LighghtEeloo/lalrpop-lsp"
rev = "07ddb62683e1786ad7986facd274f7e75ad75544"
path = "grammars/lalrpop"

[grammars.lalrpop_rust]
repository = "https://github.com/LighghtEeloo/lalrpop-lsp"
rev = "07ddb62683e1786ad7986facd274f7e75ad75544"
path = "grammars/lalrpop-rust"

[language_servers.lalrpop-lsp]
name = "LALRPOP Language Server"
languages = ["LALRPOP"]

[language_servers.lalrpop-lsp.language_ids]
LALRPOP = "lalrpop"
