[package]
name = "lalrpop-lsp"
version = "0.1.0"
edition = "2021"
description = "Language Server Protocol support for LALRPOP grammars"
license = "MIT"
repository = "https://github.com/LighghtEeloo/lalrpop-lsp"

[dependencies]
env_logger = "0.11.5"
tokio = { version = "1.42.0", features = ["full"] }
tower-lsp = { version = "0.20.0", features = ["proposed"] }
dashmap = { version = "6.1" }
lalrpop = { git = "https://github.com/LighghtEeloo/lalrpop.git", branch = "lsp", features = ["lsp"] }
